sudo: required
services:
    - docker
    
before_install:
    - docker build -t maneesh-ms/docker-sample-react -f Dockerfile.dev .

script:
    - docker run maneesh-ms/docker-sample-react npm run test -- --coverage